[project]
name = "demolay-backend"
version = "0.1.0"
description = "API Tesouraria DeMolay"
authors = [
    {name = "Luiz Fernando"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"

# --- AQUI ESTÁ A LISTA DE DEPENDÊNCIAS CORRIGIDA ---
dependencies = [
    "django (>=5.0)",
    "djangorestframework (>=3.16.1)",
    "django-cors-headers (>=4.9.0)",
    "python-decouple (>=3.8)",
    "reportlab (>=4.4.9)",
    "dj-database-url (>=2.1)",
    "whitenoise (>=6.6)",
    "psycopg2-binary (==2.9.11)",
    "gunicorn (==24.1.1)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false