# Generated by Django 6.0.1 on 2026-01-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao_id', models.CharField(max_length=50)),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Remoção')], max_length=10)),
                ('usuario', models.CharField(default='Sistema', max_length=150)),
                ('estado_anterior', models.JSONField(blank=True, null=True)),
                ('estado_novo', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SAIDA', 'Saída (-)')], max_length=10)),
                ('categoria', models.CharField(choices=[('ADM', 'Administrativo (Capítulo)'), ('FIL', 'Filantropia (Obrigatório)'), ('EVE', 'Eventos/Festas'), ('CAM', 'Campanhas Específicas')], default='ADM', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nome', models.CharField(help_text='Ex: Mensalidade Luiz, Pagamento Aluguel', max_length=150)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes adicionais', null=True)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DIN', 'Dinheiro'), ('CRED', 'Cartão de Crédito'), ('DEB', 'Cartão de Débito'), ('BOL', 'Boleto')], default='PIX', max_length=4)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data_transacao'],
            },
        ),
    ]
