# Generated by Django 6.0.1 on 2026-01-23 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auditlog_ip_origem_auditlog_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.AddField(
            model_name='transacao',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('FIL', 'Filantropia'), ('EVE', 'Eventos/Festas'), ('CAM', 'Campanhas'), ('MENSALIDADE', 'Mensalidade'), ('DOACAO', 'Doação'), ('OUTRO_ENTRADA', 'Outros (Entrada)'), ('ALUGUEL', 'Aluguel/Contas'), ('COMIDA', 'Alimentação'), ('OUTRO_SAIDA', 'Outros (Saída)')], default='OUTRO_ENTRADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DIN', 'Dinheiro'), ('CRED', 'Cartão de Crédito'), ('DEB', 'Cartão de Débito'), ('BOL', 'Boleto'), ('TRANS', 'Transferência')], default='PIX', max_length=5),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SAIDA', 'Saída (-)')], max_length=15),
        ),
    ]
