# Generated by Django 6.0.1 on 2026-01-24 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_logsistema_delete_auditlog_transacao_comprovante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dm_id', models.IntegerField(unique=True, verbose_name='ID DeMolay')),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Dia 1 do mês de referência')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='financeiro.membro')),
            ],
            options={
                'ordering': ['-mes_referencia'],
                'unique_together': {('membro', 'mes_referencia')},
            },
        ),
    ]
