# Generated by Django 6.0.1 on 2026-01-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_membro_mensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=35.0, max_digits=10, verbose_name='Valor Mensalidade (R$)')),
                ('dia_vencimento', models.IntegerField(default=10, verbose_name='Dia do Vencimento')),
                ('chave_pix', models.CharField(blank=True, default='capitulo29@demolay.org.br', max_length=255)),
                ('nome_capitulo', models.CharField(default='Capítulo Unidos da Esperança nº 29', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
